# Source code language.
language: java

# Support OpenJDK 11+
jdk:
- openjdk11

# Decrypt sftp secrets.
before_install:
- openssl aes-256-cbc
    -K $encrypted_6d162d86900c_key
    -iv $encrypted_6d162d86900c_iv
    -in src/etc/ivy/sftp.properties.enc
    -out src/etc/ivy/sftp.properties -d

# Use Ant to compile, test, package and publish.
script: ant -f src/etc/ant/build.xml ci
